### ISSUE TITLE
Singleton thread for multiple instances of the sink

### ISSUE THREAD

**Issue by jezzsantos** [jezzsantos/Serilog.Sinks.Async#6]
In [BufferedQueueSink.cs](https://github.com/jezzsantos/Serilog.Sinks.Async/blob/master/src/Serilog.Sinks.Async/BufferedQueueSink.cs#L55) we are creating a new thread (from thread pool) in `Task.Run()` to do the consumption of buffered log events for the lifetime of the instance of the sink.

In a single app deployment, such as within an ASP.NET app, that means that multiple instances of this sink (for whatever reason the developer needs them) will use a thread from the thread pool for each instance of the sink. In apps like ASP.NET thread pool threads are a premium, and tying them up waiting to consume sinks might be deemed a waste.

For example, if you have a custom logger running in a REST service (hosted in IIS) that logs  'audits' to one sink and 'counters' to another, and 'traces' to yet another sink, you will have a least 3 thread pool threads potentially blocking waiting to consume log data, that may or may not be busy depending on load.

Suggestion is to have a configuration setting that decides whether to deidcate a thread per instance of the sink, or reuse a single (singleton) general purpose thread for all sinks (one for all instances of the sink). 
If those sinks are I/O bound then there is a chance that the singleton thread could be reused concurrently, instead of being blocked waiting for consumption on one of the sinks.

Is this valuable? Is this viable?

**Comment by jezzsantos** [comment]
On reflection,

If we are trying  to save on thread pool threads (in say, an ASP.NET context) then one assumes we are trying to scale the application to meet demanding loads, and concurrent users.

In that situation, each thread pool thread that is doing anything but serving requests reduces the number of concurrent users that can access the app, and increases the cost of scaling the app (I.e. More instances in a farm).

In those situations, wouldn't we also assume that the load on any logger in that app is likely increased, and so overloading a singleton thread with sinking I/O is probably going to make logging the bottleneck of the app?

If that is the case, then having this option is only really applicable to low load applications, where logging will likely not be bottle-necked. If that is the case, then it follows that low load applications are unlikely to be worried about tying up thread pool threads doing logging.

So am I a not convinced then that this is a viable option for most cases.

Unless, someone can see a use case where it is needed?

**Comment by nblumhardt** [comment]
Given multiple sinks can possibly ship events concurrently, sharing a single thread between them could hurt throughput. Probably better to allocate a thread per instance of the sink, at a guess.
